import React from "react";
import {
  ArrowLeft,
  Calendar,
  FileText,
  Clock,
  CheckCircle,
  AlertCircle,
  Download,
  Share2,
  Edit3,
  MoreHorizontal,
} from "lucide-react";
import { Analysis } from "../types";

interface AnalysisDetailProps {
  analysis: Analysis;
  onBack: () => void;
}

export function AnalysisDetail({ analysis, onBack }: AnalysisDetailProps) {
  const getStatusIcon = (status: Analysis["status"]) => {
    switch (status) {
      case "completed":
        return <CheckCircle className="w-5 h-5 text-green-500" />;
      case "processing":
        return <Clock className="w-5 h-5 text-yellow-500" />;
      case "draft":
        return <AlertCircle className="w-5 h-5 text-gray-400" />;
    }
  };

  const getStatusBadge = (status: Analysis["status"]) => {
    const styles = {
      completed: "bg-green-100 text-green-800",
      processing: "bg-yellow-100 text-yellow-800",
      draft: "bg-gray-100 text-gray-800",
    };

    return (
      <span
        className={`px-3 py-1 rounded-full text-sm font-medium ${styles[status]}`}
      >
        {status.charAt(0).toUpperCase() + status.slice(1)}
      </span>
    );
  };

  // Sample generated content for demonstration
  const sampleContent = `# ${analysis.title}

## Executive Summary

This comprehensive analysis explores the topic of "${
    analysis.topic
  }" through an AI-powered content generation approach. Our analysis reveals key insights and opportunities for content creation and engagement.

## Key Findings

### Content Opportunities
- **High-impact keywords**: The topic shows strong search volume and engagement potential
- **Audience alignment**: Content matches target demographic interests and pain points  
- **Competitive landscape**: Moderate competition with opportunities for differentiation

### Recommended Content Strategy
1. **Primary content pillars** focusing on educational and problem-solving approaches
2. **Secondary content** targeting long-tail keywords and niche audiences
3. **Content calendar** optimized for peak engagement times and seasonal trends

## Detailed Analysis

### Market Research
The analysis indicates significant opportunities in the ${
    analysis.topic
  } space. Based on trending data and audience behavior patterns, content in this area consistently performs well across multiple platforms.

### Content Recommendations

#### Blog Posts
- Weekly long-form articles (1,500-2,500 words)
- How-to guides and tutorials
- Industry insights and trend analysis

#### Social Media Content  
- Daily engaging posts across platforms
- Visual content and infographics
- Community-building initiatives

#### Email Marketing
- Newsletter campaigns with curated content
- Automated sequences for lead nurturing
- Personalized recommendations based on user behavior

### Performance Metrics
Expected performance indicators based on similar content analyses:
- **Engagement rate**: 15-25% above industry average
- **Conversion potential**: High for educational content formats
- **SEO impact**: Strong keyword ranking opportunities identified

## Implementation Timeline

### Phase 1 (Weeks 1-2)
- Content calendar development
- Keyword research and optimization
- Initial content creation

### Phase 2 (Weeks 3-4)  
- Content publishing and promotion
- Performance monitoring and optimization
- Audience feedback integration

### Phase 3 (Ongoing)
- Regular content updates and refreshes
- Performance analysis and strategy refinement
- Expansion into new content formats and channels

## Conclusion

This analysis provides a comprehensive foundation for ${
    analysis.topic
  }-focused content creation. The insights and recommendations offer a clear path forward for developing engaging, high-performing content that resonates with the target audience.

*Generated by ContentAI on ${new Date(
    analysis.createdAt
  ).toLocaleDateString()}*`;

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white border-b border-gray-200 sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <button
              onClick={onBack}
              className="flex items-center space-x-2 text-gray-600 hover:text-gray-900 transition-colors duration-200"
            >
              <ArrowLeft className="w-5 h-5" />
              <span>Back to Dashboard</span>
            </button>

            <div className="flex items-center space-x-3">
              <button className="p-2 text-gray-600 hover:text-gray-900 hover:bg-gray-100 rounded-lg transition-all duration-200">
                <Edit3 className="w-5 h-5" />
              </button>
              <button className="p-2 text-gray-600 hover:text-gray-900 hover:bg-gray-100 rounded-lg transition-all duration-200">
                <Share2 className="w-5 h-5" />
              </button>
              <button className="p-2 text-gray-600 hover:text-gray-900 hover:bg-gray-100 rounded-lg transition-all duration-200">
                <Download className="w-5 h-5" />
              </button>
              <button className="p-2 text-gray-600 hover:text-gray-900 hover:bg-gray-100 rounded-lg transition-all duration-200">
                <MoreHorizontal className="w-5 h-5" />
              </button>
            </div>
          </div>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Analysis Header */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-8 mb-8">
          <div className="flex flex-col md:flex-row justify-between items-start gap-6">
            <div className="flex-1">
              <div className="flex items-center space-x-3 mb-4">
                <FileText className="w-6 h-6 text-blue-600" />
                <span className="text-sm font-medium text-gray-500 uppercase tracking-wide">
                  {analysis.contentType} Analysis
                </span>
              </div>

              <h1 className="text-3xl font-bold text-gray-900 mb-3">
                {analysis.title}
              </h1>

              <p className="text-gray-600 text-lg mb-6">
                {analysis.description}
              </p>

              <div className="flex flex-wrap items-center gap-4">
                <div className="flex items-center space-x-2">
                  {getStatusIcon(analysis.status)}
                  {getStatusBadge(analysis.status)}
                </div>

                <div className="flex items-center space-x-2 text-gray-500">
                  <Calendar className="w-4 h-4" />
                  <span className="text-sm">
                    Created {new Date(analysis.createdAt).toLocaleDateString()}
                  </span>
                </div>
              </div>
            </div>

            <div className="flex flex-col items-end space-y-4">
              <div className="bg-blue-100 text-blue-800 px-4 py-2 rounded-lg">
                <span className="text-sm font-medium">
                  Topic: {analysis.topic}
                </span>
              </div>

              <div className="text-right">
                <div className="text-2xl font-bold text-gray-900">
                  {analysis.wordCount.toLocaleString()}
                </div>
                <div className="text-sm text-gray-500">words generated</div>
              </div>
            </div>
          </div>
        </div>

        {/* Analysis Content */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
          <div className="p-8">
            <div className="prose prose-lg max-w-none">
              <div className="whitespace-pre-wrap text-gray-800 leading-relaxed">
                {sampleContent}
              </div>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex justify-center space-x-4 mt-8">
          <button className="bg-gradient-to-r from-blue-500 to-indigo-600 text-white px-8 py-3 rounded-lg font-semibold hover:from-blue-600 hover:to-indigo-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-all duration-200 flex items-center space-x-2">
            <Download className="w-5 h-5" />
            <span>Download PDF</span>
          </button>

          <button className="bg-white text-gray-700 px-8 py-3 rounded-lg font-semibold border border-gray-300 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 transition-all duration-200 flex items-center space-x-2">
            <Edit3 className="w-5 h-5" />
            <span>Edit Analysis</span>
          </button>
        </div>
      </main>
    </div>
  );
}
